# Generated by Django 3.2.5 on 2021-07-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='titulo',
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
