# Generated by Django 3.2.5 on 2021-07-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210721_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='titulo',
        ),
    ]
