# Generated by Django 3.2.5 on 2021-07-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20210721_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='titulo',
            new_name='title',
        ),
    ]
