# Generated by Django 3.2.5 on 2021-07-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20210726_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='categoryId',
        ),
    ]
