# Generated by Django 3.2.5 on 2021-07-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_remove_video_categoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='video.category'),
        ),
    ]
