# Generated by Django 3.2.5 on 2021-07-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_video_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.category'),
        ),
    ]
