# Generated by Django 3.2.5 on 2021-07-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_alter_video_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='video.category'),
        ),
    ]
