# Generated by Django 3.2.5 on 2021-07-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_alter_video_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='categoryId',
        ),
    ]
