# Generated by Django 3.2.5 on 2021-08-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='video.category'),
        ),
    ]
